# Generated by Django 4.1.7 on 2023-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
